In [1]:
## ROKIA SBAI 

In [2]:
## Structuration des données pour l’apprentissage

In [3]:
def structure_donnees():
    d=None
    d = {nouvelleliste: [] for nouvelleliste in range(9)} 
    import numpy as np
    nb0a = np.array([[1,1,1,1,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,1,1,1,1]])
    nb0b = np.array([[0,1,1,1,0],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [0,1,1,1,0]])

    nb1a = np.array([[0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0]])

    nb1b = np.array([[0,0,0,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,1,0,0],
        [0,0,0,0,0]])

    nb2a = np.array([[1,1,1,1,1],
        [0,0,0,0,1],
        [1,1,1,1,1],
        [1,0,0,0,0],
        [1,0,0,0,0],
        [1,1,1,1,1]])

    nb2b = np.array([[1,1,1,1,1],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,1,1,1,1],
        [1,0,0,0,0],
        [1,1,1,1,1]])

    nb3a = np.array( [[1,1,1,1,1],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,1,1,1,1],
        [0,0,0,0,1],
        [1,1,1,1,1]])

    nb3b = np.array([[1,1,1,1,1],
        [0,0,0,0,1],
        [1,1,1,1,1],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,1,1,1,1]])

    nb4a = np.array([[1,0,1,0,0],
        [1,0,1,0,0],
        [1,0,1,0,0],
        [1,1,1,1,1],
        [0,0,1,0,0],
        [0,0,1,0,0]])

    nb4b = np.array([[0,0,0,1,0],
        [0,0,1,1,0],
        [0,1,0,1,0],
        [1,1,1,1,1],
        [0,0,0,1,0],
        [0,0,0,1,0]])

    nb5a = np.array([[1,1,1,1,1],
        [1,0,0,0,0],
        [1,1,1,1,1],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,1,1,1,1]])

    nb5b = np.array([[1,1,1,1,1],
        [1,0,0,0,0],
        [1,0,0,0,0],
        [1,1,1,1,1],
        [0,0,0,0,1],
        [1,1,1,1,1]])

    nb5c = np.array([[1,1,1,1,1],
        [1,0,0,0,0],
        [1,1,1,1,0],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,1,1,1,0]])

    nb6a = np.array([[1,1,1,1,1],
        [1,0,0,0,0],
        [1,1,1,1,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,1,1,1,1]])

    nb6b = np.array([[1,1,1,1,1],
        [1,0,0,0,0],
        [1,0,0,0,0],
        [1,1,1,1,1],
        [1,0,0,0,1],
        [1,1,1,1,1]])

    nb6c = np.array([[0,1,1,1,1],
        [1,0,0,0,0],
        [1,1,1,1,0],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [0,1,1,1,0]])

    nb7a = np.array([[1,1,1,1,1],
        [0,0,0,0,1],
        [0,0,1,1,1],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [0,0,0,0,1]])

    nb7b = np.array([[1,1,1,1,1],
        [0,0,0,0,1],
        [0,0,0,1,0],
        [0,0,1,0,0],
        [0,1,0,0,0],
        [1,0,0,0,0]])

    nb8a = np.array([[1,1,1,1,1],
        [1,0,0,0,1],
        [1,1,1,1,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,1,1,1,1]])

    nb8b = np.array([[1,1,1,1,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,1,1,1,1],
        [1,0,0,0,1],
        [1,1,1,1,1]])
    
    nb8c= np.array([[0,1,1,1,0],
        [1,0,0,0,1],
        [1,1,1,1,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [0,1,1,1,0]])

    nb9a = np.array([[1,1,1,1,1],
        [1,0,0,0,1],
        [1,1,1,1,1],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,1,1,1,1]])

    nb9b = np.array([[1,1,1,1,1],
        [1,0,0,0,1],
        [1,0,0,0,1],
        [1,1,1,1,1],
        [0,0,0,0,1],
        [1,1,1,1,1]])

    nb9c = np.array([[0,1,1,1,0],
        [1,0,0,0,1],
        [0,1,1,1,1],
        [0,0,0,0,1],
        [0,0,0,0,1],
        [1,1,1,1,0]])
    d = {0:[], 1:[],2:[], 3:[], 4:[], 5:[], 6:[], 7:[], 8:[], 9:[]}
    d[0].append(nb0a.flatten())
    d[0].append(nb0b.flatten())
    d[1].append(nb1a.flatten())
    d[1].append(nb1b.flatten())
    d[2].append(nb2a.flatten())
    d[2].append(nb2b.flatten())
    d[3].append(nb3a.flatten())
    d[3].append(nb3b.flatten())
    d[4].append(nb4a.flatten())
    d[4].append(nb4b.flatten())
    d[5].append(nb5a.flatten())
    d[5].append(nb5b.flatten())
    d[5].append(nb5c.flatten())
    d[6].append(nb6a.flatten())
    d[6].append(nb6b.flatten())
    d[6].append(nb6c.flatten())
    d[7].append(nb7a.flatten())
    d[7].append(nb7b.flatten())
    d[8].append(nb8a.flatten())
    d[8].append(nb8b.flatten())
    d[8].append(nb8c.flatten())
    d[9].append(nb9a.flatten())
    d[9].append(nb9b.flatten())
    d[9].append(nb9c.flatten())
    return d

In [4]:
d=structure_donnees()

In [5]:
import numpy as np
def print_diese():
    print("#", end="")

def print_espace():
    print(" ", end="")

def print_saut_de_ligne():
    print("")
    
def print_matrice(m):
    for i in range(0,5):
        if m[i]==1:
            print_diese()
        if m[i]==0:
            print_espace()
    print_saut_de_ligne()
    for i in range(5,10):
        if m[i]==1:
            print_diese()
        if m[i]==0:
            print_espace()
    print_saut_de_ligne()
    for i in range(10,15):
        if m[i]==1:
            print_diese()
        if m[i]==0:
            print_espace()
    print_saut_de_ligne()
    for i in range(15,20):
        if m[i]==1:
            print_diese()
        if m[i]==0:
            print_espace()
    print_saut_de_ligne()
    for i in range(20,25):
        if m[i]==1:
            print_diese()
        if m[i]==0:
            print_espace()
    print_saut_de_ligne()
    for i in range(25,30):
        if m[i]==1:
            print_diese()
        if m[i]==0:
            print_espace()
    print_saut_de_ligne()



    

In [6]:
print_matrice(d[9][0])

#####
#   #
#####
    #
    #
#####


In [7]:
## Création du réseau de neurones

In [8]:
from numpy import random
def init_poids(dimEntree, dimSortie):
    random.seed(2)
    poids = None
    import numpy as np
    poids= np.random.uniform(-50, 50, size = (dimEntree,dimSortie))
    return poids

In [9]:
poids = init_poids(30, 10)
poids[0]

array([ -6.40050979, -47.40737682,   4.96624779,  -6.46776074,
        -7.96321979, -16.9665179 , -29.5351366 ,  11.92709664,
       -20.03453263, -23.31727249])

In [10]:
## Test du réseau de neurones

In [11]:
import numpy as np

def calcul_neurone(j, e, poids):
    resultat_j=0
    mult = e*poids[:,j]
    for i in mult:
        resultat_j+=i
    return resultat_j

In [12]:
print(calcul_neurone(3, d[9][0], poids))
print(calcul_neurone(9, d[9][0], poids))

-123.05645010986458
91.83223143508798


In [13]:
def calcul_reseau(e, poids):
    res=0
    resultat = []
    for j in range(10):
        mult = e*poids[:,j]
        for i in mult:
            res+=i
        resultat.append(res)
        
    return resultat

In [14]:
calcul_reseau(d[9][0], poids)

[43.86749469120408,
 -209.84727042276873,
 -102.7751303107519,
 -225.83158042061652,
 -347.952101577922,
 -333.7100781032646,
 -316.5149763756412,
 -268.73984025285444,
 -327.9703025923296,
 -236.1380711572416]

In [15]:
## Apprentissage

In [16]:
def apprendre_neurone(e, poids, j, sortie_attendue):
    h = 5
    valeur_calculee = 0
    valeur_calculee = calcul_neurone(j, e, poids)
    for i in e: 
        valeur_desiree = 0
        if sortie_attendue == j:
            valeur_desiree = 1
        else:
            valeur_desiree = 0
        poids[i][j] = poids[i][j] + (valeur_desiree - valeur_calculee) * e[i] * h
    return poids    

In [17]:
apprendre_neurone(d[9][0], poids, 8, 0)

array([[-6.40050979e+00, -4.74073768e+01,  4.96624779e+00,
        -6.46776074e+00, -7.96321979e+00, -1.69665179e+01,
        -2.95351366e+01,  1.19270966e+01,  3.23764090e+03,
        -2.33172725e+01],
       [ 1.21133833e+01,  2.91420943e+00, -3.65420055e+01,
         1.35781213e+00, -3.15560134e+01,  2.85335148e+01,
         3.53975293e+01, -5.76316262e-01,  5.66155007e+03,
        -4.20354523e+01],
       [ 5.24609012e-01, -4.34713496e+01, -7.18776724e+00,
        -4.03469084e+01, -3.72840028e+01,  9.67453090e+00,
        -2.73987999e+01, -3.93054316e+01, -2.79693793e+01,
        -1.50173715e+01],
       [-3.22125154e+00, -2.98256774e+01,  1.40406725e+01,
        -1.69301644e+00,  5.23672002e-01, -1.13107349e+01,
         2.93637454e+01,  8.00041789e+00, -3.37701401e+01,
         2.00752347e+01],
       [ 4.64551080e+01,  8.36117022e-04,  3.89520064e+01,
        -1.58386347e+01,  6.71441276e+00, -7.24540367e+00,
        -6.32527370e+00,  2.76559185e+01,  3.56041735e+00,
         4.

In [18]:
def apprendre_reseau(e, poids, sortie_attendue):
    for j in range(10):
        apprendre_neurone(e, poids, j, sortie_attendue)
        return poids

In [19]:
apprendre_reseau(d[9][0], poids, 1)

array([[-2.41911272e+03, -4.74073768e+01,  4.96624779e+00,
        -6.46776074e+00, -7.96321979e+00, -1.69665179e+01,
        -2.95351366e+01,  1.19270966e+01,  3.23764090e+03,
        -2.33172725e+01],
       [-4.15529861e+03,  2.91420943e+00, -3.65420055e+01,
         1.35781213e+00, -3.15560134e+01,  2.85335148e+01,
         3.53975293e+01, -5.76316262e-01,  5.66155007e+03,
        -4.20354523e+01],
       [ 5.24609012e-01, -4.34713496e+01, -7.18776724e+00,
        -4.03469084e+01, -3.72840028e+01,  9.67453090e+00,
        -2.73987999e+01, -3.93054316e+01, -2.79693793e+01,
        -1.50173715e+01],
       [-3.22125154e+00, -2.98256774e+01,  1.40406725e+01,
        -1.69301644e+00,  5.23672002e-01, -1.13107349e+01,
         2.93637454e+01,  8.00041789e+00, -3.37701401e+01,
         2.00752347e+01],
       [ 4.64551080e+01,  8.36117022e-04,  3.89520064e+01,
        -1.58386347e+01,  6.71441276e+00, -7.24540367e+00,
        -6.32527370e+00,  2.76559185e+01,  3.56041735e+00,
         4.

In [20]:
def apprendre(d, poids):
    for j in d:
        for i in d[j]:
            apprendre_reseau(i, poids, j)  
            return poids

In [21]:
apprendre(d, poids)

array([[ 3.88725462e+05, -4.74073768e+01,  4.96624779e+00,
        -6.46776074e+00, -7.96321979e+00, -1.69665179e+01,
        -2.95351366e+01,  1.19270966e+01,  3.23764090e+03,
        -2.33172725e+01],
       [ 5.82561564e+05,  2.91420943e+00, -3.65420055e+01,
         1.35781213e+00, -3.15560134e+01,  2.85335148e+01,
         3.53975293e+01, -5.76316262e-01,  5.66155007e+03,
        -4.20354523e+01],
       [ 5.24609012e-01, -4.34713496e+01, -7.18776724e+00,
        -4.03469084e+01, -3.72840028e+01,  9.67453090e+00,
        -2.73987999e+01, -3.93054316e+01, -2.79693793e+01,
        -1.50173715e+01],
       [-3.22125154e+00, -2.98256774e+01,  1.40406725e+01,
        -1.69301644e+00,  5.23672002e-01, -1.13107349e+01,
         2.93637454e+01,  8.00041789e+00, -3.37701401e+01,
         2.00752347e+01],
       [ 4.64551080e+01,  8.36117022e-04,  3.89520064e+01,
        -1.58386347e+01,  6.71441276e+00, -7.24540367e+00,
        -6.32527370e+00,  2.76559185e+01,  3.56041735e+00,
         4.

In [22]:
## Test du réseau de neurones

In [23]:
def main():
    import numpy as np
    d=structure_donnees()
    poids = init_poids(30, 10)
    apprendre(d, poids)
    print ('Veuillez saisir une entrée:(30 symboles 0 ou 1 séparés par une virgule)')
    strings = input()
    entrée= np.array(list(strings.split(',')), dtype=int)
    for j in d:
        for i in d[j]:  
            rep= (i==entrée).all()
            if rep == True:
                print('\n')
                print('Affichage des sorties\n')
                print(calcul_reseau(entrée, poids))
                break
            else:
                i=i+1

In [24]:
main()
## copiez et collez cet exemple qui représente d[9][0] : 1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1 

Veuillez saisir une entrée:(30 symboles 0 ou 1 séparés par une virgule)
1,1,1,1,1,1,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1


Affichage des sorties

[-9113.325694844554, -9367.040459958525, -9259.968319846508, -9383.024769956372, -9505.145291113675, -9490.903267639018, -9473.708165911392, -9425.933029788608, -9485.163492128084, -9393.331260693001]
